name: markdownr
description: Convert a URL to Markdown and share it to your favorite app.
publish_to: 'none'
version: 1.4.0+8
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  html2md: ^1.2.5
  intl: ^0.17.0
  share_plus: ^6.3.0
  receive_sharing_intent: ^1.4.5
  fluttertoast: ^8.1.1
  shared_preferences: ^2.0.15
  android_intent: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
