name: markdownr
description: Convert a URL to Markdown and share it to your favorite app.
publish_to: 'none'
version: 1.1.1+3
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.4
  html2md: ^1.2.5
  share_plus: ^4.0.7
  receive_sharing_intent: ^1.4.5
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
